# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('Command_TABLE', 'Command_TABLE'),
        ('assets', 'assets'),
        ('setup.json', '.'),
        ('version_info.py', '.'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.font',
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
        'threading',
        'subprocess',
        'json',
        'configparser',
        'logging',
        'datetime',
        'time',
        're',
        'os',
        'sys',
        'pathlib',
        'typing',
        'core',
        'core.config_manager',
        'core.error_handler',
        'core.performance_monitor',
        'core.resource_manager',
        'core.async_manager',
        'ui_parts',
        'ui_parts.ui_main',
        'ui_parts.ui_handlers',
        'ui_parts.ui_components',
        'ui_parts.ui_settings_tab',
        'ui_parts.ui_serial_interface',
        'ui_parts.ui_dos_tab',
        'ui_parts.ui_tab_manager',
        'ui_parts.ui_startup_label',
        'ui_parts.font_manager',
        'ui_parts.tooltip',
        'ui_parts.shared_config',
        'ui_parts.command_processor',
        'serial_worker',
        'adb_worker',
        'config_core',
        'config_utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='指令通_v1.9.2',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info_build.py',
    icon='assets/icon.ico'
)
